import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import {NextIntlClientProvider} from 'next-intl';
import { getLocale, getMessages } from "next-intl/server";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "iSisman - Sistem Management",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = await getLocale();
    const messages = await getMessages();

    return (
        <html lang={locale}>
            <body className={``}>
                <ThemeProvider defaultTheme="system" enableSystem attribute="class">
                    <NextIntlClientProvider messages={messages}>
                        {children}
                        <Toaster richColors expand={true} position="top-left"/>
                    </NextIntlClientProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
